app_tasks/urls.py
from django.urls import path, include
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "app_tasks"

urlpatterns = [
    path('', views.basepage, name="index"),
    path('index/', views.index, name="index"),
    path('taskdetails/', views.TaskDetail, name="taskdetails"),
    path('users', include('app_users.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_users/urls.py
from django.urls import path, include
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "app_users"

urlpatterns = [

    path('login/', views.LoginView, name="login"),
    path('logout/', views.LogoutView, name="logout"),
    path('register/', views.RegisterView, name="register"),
    path('listusers/', views.ListUsers, name="listusers"),
    path('userprofile/', views.UserProfile, name="userprofile"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

settings/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_tasks.urls')),
    path('', include('app_users.urls')),
]

app_tasks/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser


class Priority(models.Model):
    name = models.CharField(max_length=30)
    deadline = models.IntegerField(blank=False, null=False, default=0)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Status(models.Model):
    name = models.CharField(max_length=30)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Department(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class User(AbstractUser):

    access_level = models.IntegerField(blank=False, default=0)

    department = models.ForeignKey(
        "Department",
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )


class Type_task(models.Model):
    name = models.CharField(max_length=100)
    department_id = models.ForeignKey(
        "Department",
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

class Task(models.Model):
    theme = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=1000, null=True)
    created_at = models.DateTimeField(null=True)
    completion_Date_actual = models.DateTimeField(null=True)
    completion_Date_plan = models.DateTimeField(null=True)
    date_of_Adoption = models.DateTimeField(null=True)
    priority_id = models.ForeignKey(
        'Priority',
            on_delete=models.PROTECT,
            null=True,
            blank=True,
            default = 1
    )

    status_id = models.ForeignKey(
        'Status',
            on_delete=models.PROTECT,
            null=True,
            blank=True,
            default=3
    )
    department_id = models.ForeignKey(
            Department,
            on_delete=models.PROTECT,
            null=True,
            blank=True
    )
    type_task_id = models.ForeignKey(
            Type_task,
            on_delete=models.PROTECT,
            null=True,
            blank=True,
    )

    user_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="executor"
    )
    author_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="creator"
    )
    def __str__(self):
        return self.theme

app_tasks/forms.py
from django import forms
from app_tasks.models import Priority, Task, Department, Status,Type_task
from django.contrib.auth import get_user_model



class TaskDetailForm(forms.Form):

    def __init__(self, *args, **kwargs):

        super(TaskDetailForm, self).__init__(*args, **kwargs)

    class_user = get_user_model()

    task_id = forms.IntegerField(label="Заявка №",required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'readonly': 'readonly','style': 'width: 100px; text-align: center;'}))

    type_task_id = forms.ModelChoiceField(queryset=Type_task.objects, label="Тип Заявки",
                                          empty_label="Не выбран тип заявки",
                                          widget=forms.Select(attrs={'class': 'form-control'}))

    theme = forms.CharField(max_length=100, label="Тема", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите тему заявки'}))

    priority_id = forms.ModelChoiceField(queryset=Priority.objects, label="Важность",
                                         widget=forms.Select(attrs={'class': 'form-control'}))

    status_id = forms.ModelChoiceField(queryset=Status.objects, label="Статус",
                                       widget=forms.Select(attrs={'class': 'form-control'}))

    department_id = forms.ModelChoiceField(queryset=Department.objects, label="Подразделение",
                                           widget=forms.Select(attrs={'class': 'form-control'}))

    user_id = forms.ModelChoiceField(queryset=class_user.objects, label="Исполнитель",
                                     widget=forms.Select(attrs={'class': 'form-control'}))

    description = forms.CharField(max_length=1000, label="Описание", widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Введите описание заявки'}))

    completion_Date_plan = forms.DateTimeField(label="Дата выполнения (план)", required=False, widget=forms.DateTimeInput(
        attrs={'type': 'datetime-local', 'class': 'form-control datetimepicker-input'}))

    completion_Date_actual = forms.DateTimeField(label="Дата выполнения (факт)",required=False, widget=forms.DateTimeInput(
        attrs={'class': 'form-control datetimepicker-input','disabled': 'disabled'}))

    Date_of_Adoption = forms.DateTimeField(label="Дата принятия в работу",required=False, widget=forms.DateTimeInput(
        attrs={'type': 'datetime-local', 'class': 'form-control datetimepicker-input', 'disabled': 'disabled'}))

    created_at = forms.DateTimeField(label="Дата создания", required=False, widget=forms.DateTimeInput(
        attrs={'class': 'form-control datetimepicker-input', 'disabled': 'disabled'}))

    author_id = forms.ModelChoiceField(queryset=class_user.objects,required=False, label="Автор",
                                       widget=forms.Select(attrs={'class': 'form-control', 'disabled': 'disabled'}))

    class Meta:
        fields=(
            'task_id','type_task_id','theme','priority_id','status_id','description','department_id','user_id','author_id',
            'created_at','completion_Date_actual','completion_Date_plan','Date_of_Adoption',)

class TaskCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TaskCreateForm, self).__init__(*args, **kwargs)


    class_user = get_user_model()

    task_id = forms.IntegerField(label="Заявка №", required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'readonly': 'readonly', 'style': 'width: 100px; text-align: center;'}))

    type_task_id = forms.ModelChoiceField(queryset=Type_task.objects, label="Тип Заявки",
                                          empty_label="Не выбран тип заявки",
                                          widget=forms.Select(attrs={'class': 'form-control'}))

    theme = forms.CharField(max_length=100, label="Тема", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите тему заявки'}))

    priority_id = forms.ModelChoiceField(queryset=Priority.objects, label="Важность",
                                         widget=forms.Select(attrs={'class': 'form-control'}))

    status_id = forms.ModelChoiceField(queryset=Status.objects, label="Статус",
                                       widget=forms.Select(attrs={'class': 'form-control'}))

    department_id = forms.ModelChoiceField(queryset=Department.objects, label="Подразделение",
                                           widget=forms.Select(attrs={'class': 'form-control'}))

    user_id = forms.ModelChoiceField(queryset=class_user.objects,required=False, label="Исполнитель",
                                     widget=forms.Select(attrs={'class': 'form-control'}))

    description = forms.CharField(max_length=1000, label="Описание", widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Введите описание заявки'}))

    completion_Date_plan = forms.DateTimeField(label="Дата выполнения (план)",required=False, widget=forms.DateTimeInput(
        attrs={'type': 'datetime-local', 'class': 'form-control datetimepicker-input'}))

    completion_Date_actual = forms.DateTimeField(label="Дата выполнения (факт)",required=False, widget=forms.DateTimeInput(
        attrs={'class': 'form-control datetimepicker-input', 'disabled': 'disabled'}))

    Date_of_Adoption = forms.DateTimeField(label="Дата принятия в работу",required=False, widget=forms.DateTimeInput(
        attrs={'type': 'datetime-local', 'class': 'form-control datetimepicker-input', 'disabled': 'disabled'}))

    created_at = forms.DateTimeField(label="Дата создания",required=False, widget=forms.DateTimeInput(
        attrs={'class': 'form-control datetimepicker-input', 'disabled': 'disabled'}))

    author_id = forms.ModelChoiceField(queryset=class_user.objects,required=False, label="Автор",
                                       widget=forms.Select(attrs={'class': 'form-control', 'disabled': 'disabled'}))

    class Meta:
        model = Task
        fields = (
        'task_id','type_task_id', 'theme', 'priority_id', 'status_id', 'description', 'department_id', 'user_id', 'author_id',
        'created_at', 'completion_Date_actual', 'completion_Date_plan', 'Date_of_Adoption',)

app_tasks/views.py
from django.db.transaction import commit
from django.shortcuts import render, redirect
from .forms import TaskDetailForm,TaskCreateForm
from django.contrib import messages
from app_tasks.models import Type_task, Task,Priority
from django.db.models import Q
import datetime
import json


"""
Получаем список заявок
Нулевой уровень доступа: заявки, в которых автор = текущий пользователь
Первый уровень доступа: заявки, в которых автор = текущий пользователь, исполнитель= текущий пользователь
и заявки без исполнителя у которых такой же отдел как у пользователя
Второй уровень доступа: все заявки
Суперпользователь: все заявки
"""
def get_list_tasks(user):

    access_level = user.access_level

    if not  user.is_superuser:
        department_id = user.department_id

    if access_level == 2 or user.is_superuser:
        user_tasks = Task.objects.all()
        context2 = {'user_tasks': user_tasks}

    elif access_level == 0:
        user_tasks = Task.objects.filter(author_id = user.id)
        context2 = {'user_tasks': user_tasks}

    elif access_level == 1:
        user_tasks = Task.objects.filter(
            Q(author_id=user.id)|
            Q(user_id=user.id)|
            (Q(user_id__isnull=True)&
             Q(department_id=department_id))
        )
        context2 = {'user_tasks': user_tasks}

    return context2

#для корректного отображения адреса http://127.0.0.1:8000/
def basepage(request):
    return redirect('app_tasks:index')

#Вывод главной страницы
def index(request):
    if request.user.is_authenticated:

        context = get_list_tasks(request.user)

        return render(request,"index.html",context)

    else:

        return redirect('app_users:login')

#Функция для создания и редактирования заявки
def TaskDetail(request):

    if request.method == 'POST':

        if not request.POST.get('task_id_edit'):

            if request.POST.get('task_id') != '':

                form = TaskDetailForm(request.POST)

                if form.is_valid():
                    task_id = form.cleaned_data['task_id']
                    task = Task.objects.get(id=task_id)
                    if not task is None:
                        list_update_fields = []

                        if form.cleaned_data['type_task_id'] != task.type_task_id:
                            task.type_task_id = form.cleaned_data['type_task_id']
                            list_update_fields.append('first_name')

                        if form.cleaned_data['theme'] != task.theme:
                            task.theme = form.cleaned_data['theme']
                            list_update_fields.append('theme')

                        if form.cleaned_data['priority_id'] != task.priority_id:
                            task.priority_id = form.cleaned_data['priority_id']
                            list_update_fields.append('priority_id')

                        if form.cleaned_data['status_id'] != task.status_id:
                            task.status_id = form.cleaned_data['status_id']
                            list_update_fields.append('status_id')
                        if form.cleaned_data['user_id'] != task.user_id:
                            task.user_id = form.cleaned_data['user_id']
                            list_update_fields.append('user_id')

                        if form.cleaned_data['completion_Date_plan'] != task.completion_Date_plan:
                            task.completion_Date_plan = form.cleaned_data['completion_Date_plan']
                            list_update_fields.append('completion_Date_plan')

                        if list_update_fields:
                            task.save(update_fields=list_update_fields)
                        return redirect('app_tasks:index')
                    else:
                        messages.error(request, "Заявка удалена!")
                else:
                    messages.error(request, "Данные заявки некорректные!")
            else:
                form = TaskCreateForm(request.POST)

                if form.is_valid():
                    task = form.save(commit=False)
                    task.author_id = request.user
                    task.created_at = datetime.datetime.now()
                    task.save()

                    return redirect('app_tasks:index')

                else:
                    messages.error(request, "Данные заявки некорректные!")

        else:

            task_id = request.POST.get('task_id_edit')
            task = Task.objects.get(id=task_id)

            if not task is None:
                initial_data = {
                    'task_id': task.id,
                    'theme': task.theme,
                    "type_task_id": task.type_task_id,
                    "priority_id": task.priority_id,
                    "status_id": task.status_id,
                    "description": task.description,
                    "department_id": task.department_id,
                    "user_id": task.user_id,
                    "author_id": task.author_id,
                    "created_at": task.created_at,
                    "completion_Date_actual": task.completion_Date_actual,
                    "completion_Date_plan": task.completion_Date_plan,
                    "date_of_Adoption": task.date_of_Adoption,
                }
                form = TaskDetailForm(initial=initial_data)
            else:
                messages.error(request, "Возможно заявка удалена!")

                return render(request, "index.html", {'form': form})

    else:
        initial_data = {
            "author_id": request.user,
        }
        form = TaskCreateForm(initial=initial_data)

    type_task_qs = Type_task.objects.all()
    list_of_dicts_type_task = list(type_task_qs.values())
    result_dict_type_task = {d['id']: d for d in list_of_dicts_type_task}

    priority_qs = Priority.objects.all()
    list_of_dicts_priority = list(priority_qs.values())

    return render(request, 'taskdetail.html',
                  {'form': form, 'list_of_dicts_priority': json.dumps(list_of_dicts_priority),
                   'dicts_type_task': json.dumps(result_dict_type_task)})

app_tasks/templates/_base.html
<!doctype html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Helpdesk</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  </head>
  <body>

  {% if user.is_authenticated %}
  {% block mainmenu %}

		<div class="header">
			<ul id="mainmenu" class="mainmenu">
                <li class="first"><h2>Helpdesk</h2></li>
                <li class="first"><a href="{% url 'app_tasks:index' %}"><button class="btn btn-outline-success" type="submit">Заявки</button></a></li>
                <li class="first"><a href="{% url 'app_tasks:taskdetails' %}"><button class="btn btn-outline-success" type="submit">Создать заявку</button></a></li>
                {% if user.is_superuser or user.access_level == 2 %}
                <li class="first"><a href="{% url 'app_users:listusers' %}"><button class="btn btn-outline-success" type="submit">Пользователи</button></a></li>
                {% endif %}
                <li class="last"> {{user.username}} | <a href="{% url 'app_users:logout' %}"><button class="btn btn-outline-success" type="submit">Выйти</button></a></li>
            </ul>
        </div>

  {% endblock mainmenu %}
  {% endif %}

  {% block content %}

  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  </body>
</html>

app_tasks/templates/index.html
{% extends '_base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% csrf_token %}
    <div class="user-table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>Номер заявки</th>
                    <th>Тема</th>
                    <th>Автор</th>
                    <th>Исполнитель</th>
                    <th>Срок</th>
                    <th>Статус</th>
                    <th>Дата создания заявки</th>
                    <th>Приоритет</th>
                    <th>Департамент</th>
                 </tr>
            </thead>
            <tbody>
                    {% for task in user_tasks %}
                    <tr>
                        <td>
                            <form method="POST" action="{% url 'app_tasks:taskdetails' %}">
                                {% csrf_token %}
                                <input type="hidden" name="task_id_edit" value="{{task.id}}" />
                                <button type="submit" style="border:none; background:none; padding:0; margin:0; cursor:pointer; color:blue; text-decoration:underline;">
                                  {{task.id}}
                                </button>
                              </form>
                        </td>
                        <td>
                            {{ task.theme }}
                        </td>
                        <td>
                            {{ task.author_id }}
                        </td>
                        <td>
                            {{ task.user_id }}
                        </td>
                        <td>
                            {{ task.completion_Date_plan }}
                        </td>
                        <td>
                            {{ task.status_id }}
                        </td>
                        <td>
                            {{ task.created_at }}
                        </td>
                        <td>
                            {{ task.priority_id }}
                        </td>
                        <td>
                            {{ task.department_id }}
                        </td>
                    </tr>
                    {% endfor %}
	        </tbody>
        </table>
    </div>

{% endblock %}

app_tasks/templates/taskdetail.html
{% extends '_base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/task.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div class="col-6 offset-3">
    <form action="" method="post">
        {% csrf_token %}
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="


">{{ f.errors }}</div>
        {% endfor %}
         {% if not form.task_id.value %}
        <button type="submit" class="btn btn-secondary">Создать</button>
        {% else %}
        <button type="submit" class="btn btn-secondary">Сохранить</button>
        {% endif %}
    </form>
</div>

<script>
  window.djangoData = {
    DictsPriority: {{ list_of_dicts_priority|safe }},
    DictsTypeTask: {{ dicts_type_task|safe }},
  };
</script>

{% endblock content %}