app_users/urls.py
from django.urls import path, include
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "app_users"

urlpatterns = [

    path('login/', views.LoginView, name="login"),
    path('logout/', views.LogoutView, name="logout"),
    path('register/', views.RegisterView, name="register"),
    path('listusers/', views.ListUsers, name="listusers"),
    path('userprofile/', views.UserProfile, name="userprofile"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

settings/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_tasks.urls')),
    path('', include('app_users.urls')),
]

app_users/models.py
from django.db import models

# Create your models here.

app_users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from app_tasks.models import Priority, Task, Department, Status,Type_task
from django.forms import ModelForm

from datetime import datetime


#LoginForm
class LoginForm(AuthenticationForm):
    username=forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class':'form-control'}))
    password=forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class UserProfileForm(forms.Form):

    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control','readonly':'readonly'}))
    email = forms.CharField(label='Эл.почта', widget=forms.TextInput(attrs={'class': 'form-control'}))
    #password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    #password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
    department = forms.ModelChoiceField(queryset=Department.objects, label="Подразделение",
                                        widget=forms.Select(attrs={'class': 'form-control'}))
    access_level = forms.IntegerField(label='Уровень доступа',min_value=0, max_value=2, widget=forms.NumberInput())

    class Meta:
        fields = ('username', 'email', 'first_name', 'last_name', 'department','access_level',)

    def clean(self):
        email       = self.cleaned_data['email']
        username    = self.cleaned_data['username']
        if get_user_model().objects.filter(email=email).exists() and get_user_model().objects.get(email=email).username != username:
            raise forms.ValidationError("Такой E-mail уже существует!")

#RegisterForm
class RegisterUserForm(UserCreationForm):

    first_name      = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name       = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
    username        = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email           = forms.CharField(label='Эл.почта', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1       = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2       = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    department      = forms.ModelChoiceField(queryset=Department.objects, label="Подразделение",widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model=get_user_model()
        fields=('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'department')

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

app_users/views.py
from django.shortcuts import render, redirect

import app_tasks.views
from .forms import LoginForm, RegisterUserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from django.contrib.auth import get_user_model


def ListUsers(request):

    class_user = get_user_model()
    users = class_user.objects.filter(is_superuser = False)

    return render(request,"ListUsers.html",{'users':users})

def UserProfile(request):

    if request.method == 'POST':

        form = UserProfileForm(request.POST)

        if not request.POST.get('user_id'):

          if form.is_valid():
                username = form.cleaned_data['username']
                class_user = get_user_model()
                user = class_user.objects.get(username=username)
                if not user is None:
                    list_update_fields = []

                    if form.cleaned_data['first_name'] != user.first_name:
                        user.first_name = form.cleaned_data['first_name']
                        list_update_fields.append('first_name')

                    if form.cleaned_data['last_name'] != user.last_name:
                        user.last_name = form.cleaned_data['last_name']
                        list_update_fields.append('last_name')

                    if form.cleaned_data['email'] != user.email:
                        user.email = form.cleaned_data['email']
                        list_update_fields.append('email')

                    if form.cleaned_data['department'] != user.department:
                        user.department = form.cleaned_data['department']
                        list_update_fields.append('department')

                    if form.cleaned_data['access_level'] != user.access_level:
                        user.access_level = form.cleaned_data['access_level']
                        list_update_fields.append('access_level')

                    if list_update_fields:
                        user.save(update_fields=list_update_fields)

                else:
                    messages.error(request, "Пользователь удален!")

                users = class_user.objects.filter(is_superuser=False)

                return render(request, "ListUsers.html", {'form': form, 'users': users})

          else:
            messages.error(request, "Данные пользователя некорректные!")
        else:

            id = request.POST.get('user_id')
            class_user = get_user_model()
            user = class_user.objects.get(id=id)

            if not user is None:
                initial_data = {
                    'username': user.username,
                    'email': user.email,
                    'first_name':user.first_name,
                    'last_name': user.last_name,
                    'department': user.department,
                    'access_level': user.access_level,
                    }
                form = UserProfileForm(initial=initial_data)
            else:
                messages.error(request, "Пользователь удален!")

                users = class_user.objects.filter(is_superuser=False)

                return render(request, "ListUsers.html", {'form': form, 'users': users})

    else:
        form = UserProfileForm()

    return render(request, 'UserProfile.html', {'form': form})

#LoginView
def LoginView(request):
    if request.method =='POST':
        form=LoginForm(data=request.POST)

        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(request,username=username,password=password)

            if user is not None:

                login(request,user)

                return redirect('app_tasks:index')

            else:
                messages.error(request,"Вход не выполнен!")

        else:
            messages.error(request, "Не удалось авторизоваться!")

    else:
        form=LoginForm()

    return render(request, 'login.html',{'form':form})

#Выход из аккаунта пользователя
def LogoutView(request):
    logout(request)
    # messages.success(request, "Выход осуществлен!")
    return redirect('app_users:login')


def RegisterView(request):
    if request.method == 'POST':
        Register_form = RegisterUserForm(request.POST)
        if Register_form.is_valid():
            user = Register_form.save(commit=False)
            user.set_password(Register_form.cleaned_data['password1'])
            user.save()
            # messages.success(request, "Вы успешно зарегистрировались!")
            return redirect('app_users:login')
        else:
            messages.error(request, "Данные для регистрации некорректные!")
            return render(request, 'register.html', {'form': Register_form})
    else:
        Register_form = RegisterUserForm()
        return render(request, 'register.html', {'form': Register_form})

app_users/templates/listusers.html
{% extends '_base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="form-main">
{% csrf_token %}
    <div class="user-table-container">
        <table class="table_users">
            <thead>
                <tr>
                    <th>Департамент</th>
                    <th>Пользователь</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Уровень доступа</th>
                 </tr>
            </thead>
            <tbody>
                    {% for user in users %}
                    <tr>
                        <td>
                            {{ user.department }}
                        </td>
                        <td>
                             <form method="POST" action="{% url 'app_users:userprofile' %}">
                                {% csrf_token %}
                                <input type="hidden" name="user_id" value="{{user.id}}" />
                                <button type="submit" style="border:none; background:none; padding:0; margin:0; cursor:pointer; color:blue; text-decoration:underline;">
                                  {{user.username}}
                                </button>
                              </form>
                        </td>
                        <td>
                            {{ user.first_name }}
                        </td>
                        <td>
                            {{ user.last_name }}
                        </td>
                        <td>
                            {{ user.access_level }}
                        </td>
                    </tr>
                    {% endfor %}
	        </tbody>
        </table>
    </div>
</div>
{% endblock %}

app_users/templates/login.html
{% extends '_base.html' %}
{% block content %}
<div class="col-4 offset-3">
    <h2>Авторизация</h2>
    <form action="" method="post" autocomplete="off">
        {% csrf_token %}
        {% for f in form %}
            <p><label class="form-label"> {{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-secondary">Войти</button>
        <button type="submit" class="btn btn-secondary"> <a href="{% url 'app_users:register' %}"class="text-decoration-none text-reset">Зарегистрироваться</a></button>
    </form>
</div>
{% endblock content %}

app_users/templates/register.html
{% extends '_base.html' %}
{% block content %}
<div class="col-4 offset-3">
    <h1>Форма регистрации</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% for f in form %}
        <p><label class="form-label"> {{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-secondary">Зарегистрироваться</button>
    </form>
</div>
    {% endblock content %}

app_users/templates/userprofile.html
{% extends '_base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="col-4 offset-3">
<h1>Профиль</h1>

<form action="{% url 'app_users:userprofile' %}" method="post">
    {% csrf_token %}
    {% if user.photo %}
    <p><img src="{{ user.photo.url }}">
    {% else %}
    <p><img src="{{ default_image }}">
    {% endif %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>

</form>
</div>
{% endblock %}